[versions]

agp = "8.12.3"
kotlin = "2.2.20"

androidx-core = "1.17.0"
androidx-appcompat = "1.7.1"
androidx-activity = "1.11.0"
google-material = "1.13.0"

[libraries]

androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
